
---
output:
  html_document: default
  pdf_document:
    fig_caption: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=5,fig.align = "center",cache=TRUE)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
##libraries, globals

library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(summarytools)
library(MuMIn)
library(stargazer)

paper_theme <- theme_light()


```


```{r}
data <- read.csv('data.csv')

data <- data %>%
        mutate(corr = (n_shown == n_guess)*1) %>%
        mutate(high_jitter = jitter > 20) 


data$color <- factor(data$color)
data$id <- seq.int(1,nrow(data))


data.resp <- data %>%
            group_by(trial_id, pid) %>%
            top_n(n=1, wt=id) 
```


```{r}

#ggplot(data=data, aes(x=loc_x, y=loc_y, color=color)) +
   #   geom_point() +
   #   facet_wrap(~jitter~trial_id~pid) +
  #    paper_theme + 
   #   theme(  strip.text=element_blank(),
  #        strip.background = element_blank())



```


```{r}

ggplot(data=data.resp, aes(x=n_shown, y=n_guess)) +
        #stat_summary(fun.data="mean_se") +
        geom_point() + 
        paper_theme







```